apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "myapp.fullname" .}}
data:
data:
  default.json: |
    {
      "network": {
        "port": "80"
      },
      "environment": {
        "SSL": false
      },
      "redis": {
        "server": "{{ .Release.Name }}-redis-master".
        "port": "6379"
      }
    }

{{-/*
Remove this. For version 2.1.0 0.2.0 with redis need to add redis configuration
See above
{{ (.Files.Glob "config/*").AsConfig | indent 4 }}
*/}}

{{- /*
# METHOD 2 above for mutliple config files using glob
# NOTE the default.json: | has been removed
# If have different file type can use config/*.json and config/*.ini and so on......
# METHOD 2 above for mutliple config files using glob
# If have different file type can use config/*.json and config/*.ini and so on......
# Note that the .Files.Glob returns a "files" object that must be passed to the AsConfig method for proper processing of
# the file contents themselves and to render the contexts in the completed yaml file. 
# The Get method below reads the contents of the file directly.


#  default.json: |
#{{ .Files.Get "default.json" | indent 4 }}
#
# METHOD 1: the files contents cna be placed here or better do the following above and put the default.json one directory up with Chart.yaml
# NOTE that .Files.Get works off of the root directory of the helm chart so one directory up with the Chart.yaml is where 
# the default.json file should be placed; not in the templates directory



#  METHOD 0: ALTERNATE mehtod for small config json files is to put the entire contents in this configmap.yaml file like this:
#  apiVersion: v1
#  kind: ConfigMap
#  metadata:
#    name: {{ include "myapp.fullname" .}}
#  data:
#    default.json: |
#    {
#     "network": {
#         "port": "80"
#     },
#     "environment": {
#         "SSL": false
#     }
#   }
*/}}
