apiVersion: v1
kind: Secret
metadata:
  name: {{ include "myapp.fullname" . }}
type: Opaque
data:
  APIKEY: {{ "95f3a18a9emsh01f5e2c470db040p14db5cjsndb92264cbf39" | b64enc }}
    # put this file in .gitignore
