apiVersion: apps/v1
kind: Deployment
# need to make deployment name unique so add -blue to the hame
metadata:
  name: {{ include "advanced-deployments.fullname" . }}-blue
  labels:
    {{- include "advanced-deployments.labels" . | nindent 4 }}
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "advanced-deployments.selectorLabels" . | nindent 6 }}
      # add app: blue
      app: blue
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "advanced-deployments.selectorLabels" . | nindent 8 }}
        # add app: blue to the labels to differentiate it from the green deployment
        app: blue
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "advanced-deployments.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          # create a blue-vol for the configmap for the blue deployment
          volumeMounts:
            - name: blue-vol
              mountPath: /usr/share/nginx/html/index.html
              subPath: index.html
          ports:
            - name: http
              containerPort: 80
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /
              port: http
          readinessProbe:
            httpGet:
              path: /
              port: http
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      # volume for the blue-vol volumeMount above
      volumes:
        - name: blue-vol
          configMap:
            name: blue
