apiVersion: v1
kind: ConfigMap
metadata:
  name: blue
# this is the index.html page for the blue deployment
data:
  index.html: |
    <html>
      <head>
        <title>Blue</title>
      <head>
      <body>
        <h1 style="color: blue">Blue</h1>
      </body>
    </html>
