apiVersion: v1
kind: Service
metadata:
  name: {{ include "advanced-deployments.fullname" . }}
  labels:
    {{- include "advanced-deployments.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  # the selector to redirect traffic to the blue or green will use the .Values.currentTarget variable below
  selector:
    {{- include "advanced-deployments.selectorLabels" . | nindent 4 }}
    {{ toYaml .Values.currentTarget | nindent 4 }}
