apiVersion: v2

# the new app version is 2.1.0. 2.0.0 was for weatherapp API hook and this is adding redis caching to the app.
appVersion: "2.1.0"

# the dependencies block is for the redis server that will provide caching for API calls.
# need to specify the version of the redis server
# ^15.x is greater than or equal to 15.0.0 and less than 16.0.0
# I am not sure if this is still available. Try it out. If not use the version 16 as shown in 
# helm search repo "redis" --versions    version: ~15.3.x will cover 15.3.0  and less than 15.4.0
# right now 16.11.2 through 16.13.2 are in the repo.
# NOTE that the 16 chart versions are APP version 6.2.7 which is close to the 6.2.5 that original myapp was built for
# ITERATION 1
dependencies:
  - name: redis
    #version: ^15.x
    version: 16.13.2
    repository: https://charts.bitnami.com/bitnami

# ITERATION 2:
# dependencies:
# - import-values:
#   - child: master
#     parent: imported
#   name: redis
#   repository: https://charts.bitnami.com/bitnami
#   version: ^15.x


description: A weather application written for NodeJS with added redis caching for API calls
name: myapp
type: application

# this is the chart version. 0.2.0 since this is a major app change (adding redis server)
version: 0.2.0
