apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "myapp.fullname" .}}
data:
  default.json: |
{{ .Files.Get "default.json" | indent 4 }}
# the files contents cna be placed here or better do the following above and put the default.json one directory up with Chart.yaml
# NOTE that .Files.Get works off of the root directory of the helm chart so one directory up with the Chart.yaml is where 
# the default.json file should be placed; not in the templates directory
