{{- $ports := .Values.service.ports -}}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "myapp.fullname" . }}
  labels:
    {{- include "myapp.labels" . | nindent 4 }}
  annotations:
    mainPort: "{{ (index $ports 0 ).number }}"
spec:
  type: {{ .Values.service.type }}
  ports:
  {{- range $key, $value := $ports }}
    - port: {{ .number }}
      protocol: TCP
      targetPort: {{ .targetPort }}
      name: {{ .name }}
  {{- end }}
  selector:
    {{- include "myapp.selectorLabels" . | nindent 4 }}
